### PR TITLE
Update fonts to v55

### PR DESCRIPTION
**Pull request by fabiomartino**
- Extracted code from latest Material Icon V55
- Added the codepoint list and updated with latest code.
- Sort the codepoints "_variables.scss" and "MaterialIcons-Regular.json" 

```console
5g ef38
ad_units ef39
add_business e729
add_location_alt ef3a
add_road ef3b
add_g_drive e65c
addchart ef3c
admin_panel_settings ef3d
agricolture ea79
alt_route f184
analytics ef3e
anchor f1cd
animation e71c
api f1b7
app_blocking ef3f
app_registration ef40
app_settings_alt ef41
architecture ea3b
arrow_circle_down f181
arrow_circle_up f182
article ef42
attach_email ea5e
auto_awesome e65f
auto_awesome_mosaic e660
auto_awesome_motion e661
auto_delete ea4c
auto_fix_high e663
auto_fix_normal e664
auto_fix_off e665
auto_stories e666
baby_changing_station f19b
backpack f19c
backup_table ef43
batch_prediction f0f5
bedtime ef44
bento f1f4
bike_scooter ef45
biotech ea3a
block_flipped ef46
browser_not_supported ef47
build_circle ef48
calculate ea5f
campaign ef49
carpenter f1f8
cast_for_education efec
charging_station f19d
checkroom f19e
circle ef4a
cleaning_services f0ff
close_fullscreen f1cf
closed_caption_disabled f1dc
comment_bank ea4e
construction ea3c
corporate_fare f1d0
countertops f1f7
design_services f10a
directions_off f10f
dirty_lens ef4b
do_not_step f19f
do_not_touch f1b0
domain_verification ef4c
drive_file_move e675
dry f1b3
dynamic_form f1bf
east f1df
edit_road ef4d
electric_bike eb1b
electric_car eb1c
electric_moped eb1d
electric_rickshaw eb1e
electric_scooter eb1f
electrical_services f102
elevator f1a0
engineering ea3d
escalator f1a1
escalator_warning f1ac
face_retouching_natural ef4e
fact_check f0c5
family_restroom f1a2
fence f1f6
filter_alt ef4f
fire_extinguisher f1d8
fire_hydrant f1a3
flaky ef50
food_bank f1f2
forward_to_inbox f187
foundation f200
grading ea4f
grass f205
handyman f10b
hdr_enhanced_select ef51
hearing_disabled f104
help_center f1c0
highlight_alt ef52
history_edu ea3e
history_toggle_off f17d
home_repair_service f100
horizontal_rule f108
hourglass_bottom ea5c
hourglass_disabled ef53
hourglass_top ea5b
house_siding f202
hvac f10e
image_not_supported f116
insights f092
integration_instructions ef54
ios_share e6b8
legend_toggle f11b
local_fire_department ef55
local_police ef56
location_pin f1db
lock_clock ef57
login ea77
maps_ugc ef58
mark_chat_read f18b
mark_chat_unread f189
mark_email_read f18c
mark_email_unread f18a
mediation efa7
medical_services f109
mic_external_off ef59
mic_external_on ef5a
microwave f204
military_tech ea3f
miscellaneous_services f10c
model_training f0cf
monitor ef5b
moped eb28
more_time ea5d
motion_photos_off e9c0
motion_photos_on e9c1
motion_photos_pause e9c2
multiple_stop f1b9
nat ef5c
near_me_disabled f1ef
next_plan ef5d
night_shelter f1f1
nightlight_round ef5e
no_cell f1a4
no_drinks f1a5
no_flash f1a6
no_food f1a7
no_meals f1d6
no_photography f1a8
no_stroller f1af
no_transfer f1d5
north f1e0
north_east f1e1
north_west f1e2
not_accessible f0fe
not_started f0d1
online_prediction f0eb
open_in_full f1ce
outbox ef5f
outgoing_mail f0d2
outlet f1d4
panorama_horizontal_select ef60
panorama_vertical_select ef61
panorama_wide_angle_select ef62
payments ef63
pedal_bike eb29
pending ef64
pending_actions f1bb
person_add_alt ea4d
person_add_alt_1 ef65
person_remove ef66
person_remove_alt_1 ef67
person_search f106
pest_control f0fa
pest_control_rodent f0fd
photo_camera_back ef68
photo_camera_front ef69
plagiarism ea5a
play_disabled ef6a
plumbing f107
point_of_sale f17e
preview f1c5
privacy_tip f0dc
psychology ea4a
public_off f1ca
push_pin f10d
qr_code ef6b
qr_code_scanner f206
quickreply ef6c
read_more ef6d
receipt_long ef6e
request_quote f1b6
rice_bowl f1f5
roofing f201
room_preferences f1b8
rule f1c2
rule_folder f1c9
run_circle ef6f
science ea4b
screen_search_desktop ef70
search_off ea76
self_improvement ea78
sensor_door f1b5
sensor_window f1b4
set_meal f1ea
shopping_bag f1cc
signal_cellular_0_bar f0a8
signal_wifi_0_bar f0b0
smart_button f1c1
snippet_folder f1c7
soap f1b2
source f1c4
south f1e3
south_east f1e4
south_west f1e5
sports_bar f1f3
stairs f1a9
star_border f06f
star_rate f0ec
sticky_note_2 f1fc
stop_circle ef71
stroller f1ae
subscript f111
subtitles_off ef72
superscript f112
support ef73
support_agent f0e2
switch_left f1d1
switch_right f1d2
table_rows f101
table_view f1be
tapas f1e9
taxi_alert ef74
text_snippet f1c6
topic f1c8
tour ef75
tty f1aa
umbrella f1ad
upgrade f0fb
verified ef76
video_settings ea75
view_sidebar f114
wash f1b1
water_damage f203
west f1e6
wheelchair_pickup f1ab
wifi_calling ef77
wifi_protected_setup f0fc
wine_bar f1e8
wrong_location ef78
wysiwyg f1c3
leaderboard f20c
6_ft_apart f21e
book_online f217
clean_hands f21f
connect_without_contact f223
coronavirus F221
elderly f21a
follow_the_signs f222
leave_bags_at_home f21b
masks f218
reduce_capacity f21c
sanitizer f21d
send_to_mobile f05c
sick f220
add_task f23a
contact_page f22e
disabled_by_default f230
facebook f234
groups f233
luggage f235
motion_photos_paused f227
no_backpack f237
no_luggage f23b
no_meals_outline f229
outbond f228
published_with_changes f232
request_page f22c
stacked_line_chart f22b
unpublished f236

align_horizontal_center e00f
align_horizontal_left e00d
align_horizontal_right e010
align_vertical_bottom e015
align_vertical_center e011
align_vertical_bottom e00c
horizontal_distribute e014
qr_code_2 e00a
update_disabled e075
vertical_distribute e076
```

### CODE REVIEW

**Comment by daimoonis** [comment]
Hello, if you are interested in codepoints matches i made an extract from font from your updated .woff file source (dist/fonts/MaterialIcons-Regular.woff). Have a look at https://github.com/daimoonis/material-icons-font/blob/master/codepoints.json (the sort is different and one duplicate definition was removed).

**Comment by fabiomartino** [comment]
> Hello, if you are interested in codepoints matches i made an extract from font from your updated .woff file source (dist/fonts/MaterialIcons-Regular.woff). Have a look at https://github.com/daimoonis/material-icons-font/blob/master/codepoints.json (the sort is different and one duplicate definition was removed).

THX I figure out missed codepoints...
I double check missed reference in your list....
this is duplicated "E83A" and the "F06F" is missed
```bash
    "star_outline": "E83A",
    "star_border": "E83A",
```

```bash
    "star_border": F06F,
```

Cordially

**Comment by DemigodCode** [comment]
Hey, would really apprciate if this PR would be merged.

**Comment by Tofandel** [comment]
@jossef Could we get this update? Thanks

**Comment by jossef** [comment]
sorry for the delays
yes, will take care of it now

**Comment by jossef** [comment]
hey guys, thanks for the PR
Note that I already have a script that extracts the ligatures and outputs a json
https://github.com/jossef/material-design-icons-iconfont/blob/master/build/build.js

**Pull request merged**
